import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Navbar from "./component/Navbar";
import { SearchProvider } from "./SearchProvider";
import PageTransitionWrapper from "./PageTransitionWrapper";
import React from "react";
import { ToastContainer } from "react-toastify";
import Footer from "./component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "StreamIT",
  description: "Generated by create next app",
};

const RootLayout=({ children })=> {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer />
        <AuthProvider>
          <SearchProvider>
            <Navbar />
            <PageTransitionWrapper>{children}</PageTransitionWrapper>
          </SearchProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

export default RootLayout
